#words_play

"""
Django settings for words_play project.

Generated by 'django-admin startproject' using Django 3.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TAMPLATE_DIR =  BASE_DIR.joinpath("templates")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=ovko6tb^d9q@97k6yfug_9r3$_e5)g-c&3-ixm74ot=l6h6m$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    #added apps:
    'accounts',
    'game_app',
    # for FB:
    'social_django',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # Social Auth

]

ROOT_URLCONF = 'words_play.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TAMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  #For Social auth
                'social_django.context_processors.login_redirect', # For Social auth
            ],
        },
    },
]

WSGI_APPLICATION = 'words_play.wsgi.application'

#for FB
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    # 'social_core.backends.facebook.FacebookOAuth2',
    # 'social_core.backends.twitter.TwitterOAuth',
    # 'social_core.backends.github.GithubOAuth2',

    'django.contrib.auth.backends.ModelBackend',


)




#for FB
SOCIAL_AUTH_FACEBOOK_KEY = '351321751168467'
SOCIAL_AUTH_FACEBOOK_SECRET = '3f3c7c91a63f73bcfc0b7fd311d51993'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1011099681160-pdrp2oc1l6i5ves165k324lmrtbd1jpb.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/images/'

STATICFILES_DIRS =  [BASE_DIR.joinpath("static")]
MEDIA_ROOT =  BASE_DIR.joinpath("static/images")
#STATIC_ROOT =  BASE_DIR.joinpath("static")

LANGUAGES = [
    ('en', _('English')),
    ('uk', _('Ukrainian')),
    # Add more languages if needed
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Set the default language
LANGUAGE_CODE = 'uk'  # Change to 'en' for EN. Uk is for Ukranian


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
#this is needed for us to he redirected automatically to these pages after loging/logout
LOGIN_REDIRECT_URL = "test"
LOGOUT_REDIRECT_URL = "thanks"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
