# Generated by Django 3.2.21 on 2023-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='masked_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
