# Generated by Django 3.2.21 on 2023-10-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_auto_20231027_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='call_to_action',
            field=models.CharField(default='Ok make your choise now!', max_length=100),
        ),
    ]
