# Generated by Django 3.2.21 on 2023-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_word_call_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='number_of_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
