# Generated by Django 3.2.21 on 2023-11-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0007_word_you_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='game_over',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='word',
            name='you_win',
            field=models.CharField(default='Game Over Dude. Try again!', max_length=100),
        ),
    ]
