# Generated by Django 3.2.21 on 2023-11-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_auto_20231103_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='you_win',
            field=models.CharField(default='Game over. Try again!', max_length=100),
        ),
    ]
