# Generated by Django 3.2.21 on 2023-11-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_alter_word_you_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='game_over',
            field=models.CharField(default='Game Over. Try again!', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='you_win',
            field=models.CharField(default='Congrats! You have GUESSED IT!!!!', max_length=100),
        ),
    ]
