# Generated by Django 3.2.21 on 2023-11-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0010_auto_20231103_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='guessed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guessed_words', to='game_app.guessed'),
        ),
    ]
