# Generated by Django 3.2.21 on 2023-11-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0011_auto_20231110_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='guessed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Guessed',
        ),
    ]
