# Generated by Django 3.2.21 on 2023-11-16 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0013_usergame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGame',
            new_name='Profile',
        ),
    ]
