# Generated by Django 3.2.21 on 2023-11-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0014_rename_usergame_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='word',
        ),
    ]
