# Generated by Django 3.2.21 on 2023-11-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0015_remove_profile_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='number_of_attempts',
        ),
        migrations.AddField(
            model_name='profile',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.word'),
        ),
    ]
