# Generated by Django 3.2.21 on 2023-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0016_auto_20231117_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='word',
        ),
        migrations.AddField(
            model_name='profile',
            name='words',
            field=models.ManyToManyField(to='game_app.Word'),
        ),
    ]
