# Generated by Django 3.2.21 on 2023-11-21 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0018_auto_20231121_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='profile',
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
    ]
