# Generated by Django 3.2.21 on 2023-11-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0021_auto_20231123_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
