# Generated by Django 3.2.21 on 2023-11-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0024_remove_profile_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='masked_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.profile'),
        ),
    ]
