# Generated by Django 3.2.21 on 2023-12-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0025_remove_profile_number_of_attempts_to_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='number_of_attempts_to_guess',
            field=models.IntegerField(default=3),
        ),
    ]
