# Generated by Django 3.2.21 on 2023-11-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0025_alter_word_masked_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='masked_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
