# Generated by Django 3.2.21 on 2023-11-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0026_profile_masked_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='masked_word',
        ),
    ]
