# Generated by Django 3.2.21 on 2023-11-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0027_remove_word_masked_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='masked_word',
        ),
        migrations.AddField(
            model_name='word',
            name='masked_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.profile'),
        ),
    ]
