# Generated by Django 3.2.21 on 2023-11-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0030_rename_masked_word_word_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='profile',
        ),
        migrations.AddField(
            model_name='word',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
