# Generated by Django 3.2.21 on 2023-11-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0033_auto_20231127_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='profile',
        ),
    ]
