# Generated by Django 3.2.21 on 2023-11-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0034_remove_word_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='word',
            name='number_of_letter',
        ),
        migrations.AddField(
            model_name='profile',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_letter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
