# Generated by Django 3.2.21 on 2023-12-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0026_word_number_of_attempts_to_guess'),
        ('game_app', '0035_auto_20231128_0727'),
    ]

    operations = [
    ]
