# Generated by Django 3.2.21 on 2023-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0036_merge_20231208_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='word',
            name='failure',
        ),
        migrations.RemoveField(
            model_name='word',
            name='game_over',
        ),
        migrations.RemoveField(
            model_name='word',
            name='guessed',
        ),
        migrations.RemoveField(
            model_name='word',
            name='number_of_attempts_to_guess',
        ),
        migrations.RemoveField(
            model_name='word',
            name='success',
        ),
        migrations.RemoveField(
            model_name='word',
            name='you_win',
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_attempts_to_guess',
            field=models.IntegerField(default=3),
        ),
    ]
