# Generated by Django 3.2.21 on 2023-12-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0038_auto_20231208_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guessed_word',
        ),
        migrations.AlterField(
            model_name='guessedwords',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guessed_words', to='game_app.profile'),
        ),
    ]
