# Generated by Django 3.2.21 on 2023-12-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0039_auto_20231210_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guessedwords',
            name='word',
        ),
        migrations.AddField(
            model_name='guessedwords',
            name='guessed_word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guessedwords',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.profile'),
        ),
    ]
