# Generated by Django 3.2.21 on 2023-12-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0041_alter_guessedwords_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessedwords',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.profile'),
        ),
    ]
