# Generated by Django 3.2.21 on 2023-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0043_alter_guessedwords_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
