# Generated by Django 3.2.21 on 2024-01-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0044_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
