# Generated by Django 3.2.21 on 2024-01-13 10:20

from django.db import migrations
import json
from  game_app.models import Word

DATA_PATH = "/Users/oleh.shmidt/Documents/python/Django_practice/Clone_projects/ my_projects/words_game/game_app/migrations/words.json"

def load_data_from_json(apps, schema_editor):
    Word = apps.get_model('game_app', 'Word')

    with open(DATA_PATH, 'r') as file:
        data = json.loads(file.read())

    for item in data:
        Word.objects.create(
            word=item['word'],
            description=item['description'],
            category=item['category'],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0045_word_category'),
    ]

    operations = [
        migrations.RunPython(load_data_from_json),
    ]
