# Generated by Django 3.2.21 on 2024-02-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0050_auto_20240114_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_letter',
        ),
    ]
