# Generated by Django 3.2.21 on 2024-02-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0052_guessedwords_guessed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_guessed_words',
            field=models.IntegerField(null=True),
        ),
    ]
