# Generated by Django 3.2.21 on 2024-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0053_profile_number_of_guessed_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_guessed_words',
            field=models.IntegerField(default=3),
        ),
    ]
