# Generated by Django 3.2.21 on 2024-03-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0055_alter_profile_number_of_guessed_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_pics/'),
        ),
    ]
