# Generated by Django 3.2.21 on 2024-03-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0059_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to=''),
        ),
    ]
