# Generated by Django 3.2.21 on 2024-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0060_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
