# Generated by Django 3.2.21 on 2024-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0061_profile_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='raiting',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
