# Generated by Django 3.2.21 on 2024-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0062_auto_20240307_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.CharField(blank=True, default='Поки що ви нічого не відгадали, тому ви на останньому місці', max_length=100, null=True),
        ),
    ]
