# Generated by Django 3.2.21 on 2024-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0065_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
